config/routes.rb
Rails.application.routes.draw do
  resources :import_errors
  resources :lead_errors
  resources :leads do
    resources :lead_errors
  end
  resources :imports do
    resources :import_errors
  end
  devise_for :users
  get "/columns", to: "column#index"
  mount Sidekiq::Web => "/sidekiq"
  root to: "imports#index"
end

app/models/import_error.rb
class ImportError < ApplicationRecord
  belongs_to :import
end

app/controllers/import_errors_controller.rb
class ImportErrorsController < ApplicationController
  before_action :set_import_error, only: %i[ show edit update destroy ]

  # GET /import_errors or /import_errors.json
  def index
    @import_errors = current_user.import_errors.paginate(page: params[:page])
    @import_errors = @import_errors.where(import_id: params[:import_id]) if params[:import_id].present?
  end

  # GET /import_errors/1 or /import_errors/1.json
  def show
  end

  # GET /import_errors/new
  def new
    @import_error = ImportError.new
  end

  # GET /import_errors/1/edit
  def edit
  end

  # POST /import_errors or /import_errors.json
  def create
    @import_error = ImportError.new(import_error_params)

    respond_to do |format|
      if @import_error.save
        format.html { redirect_to @import_error, notice: "Import error was successfully created." }
        format.json { render :show, status: :created, location: @import_error }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @import_error.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /import_errors/1 or /import_errors/1.json
  def update
    respond_to do |format|
      if @import_error.update(import_error_params)
        format.html { redirect_to @import_error, notice: "Import error was successfully updated." }
        format.json { render :show, status: :ok, location: @import_error }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @import_error.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /import_errors/1 or /import_errors/1.json
  def destroy
    @import_error.destroy
    respond_to do |format|
      format.html { redirect_to import_errors_url, notice: "Import error was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_import_error
      @import_error = current_user.import_errors.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def import_error_params
      params.require(:import_error).permit(:import_id, :column, :value, :description)
    end
end

app/helpers/import_errors_helper.rb
module ImportErrorsHelper
end

app/views/import_errors/_form.html.erb
<%= form_with(model: import_error) do |form| %>
  <% if import_error.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(import_error.errors.count, "error") %> prohibited this import_error from being saved:</h2>

      <ul>
        <% import_error.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :import_id %>
    <%= form.text_field :import_id %>
  </div>

  <div class="field">
    <%= form.label :column %>
    <%= form.text_field :column %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/import_errors/edit.html.erb
<h1>Editing Import Error</h1>

<%= render 'form', import_error: @import_error %>

<%= link_to 'Show', @import_error %> |
<%= link_to 'Back', import_errors_path %>

app/views/import_errors/index.html.erb
<h1>Import Errors</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Import</th>
      <th scope="col">Column</th>
      <th scope="col">Value</th>
      <th scope="col">Description</th>
      <th scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% @import_errors.each do |import_error| %>
      <tr>
        <td scope="row"><%= import_error.import_id %></td>
        <td><%= import_error.column %></td>
        <td><%= import_error.value %></td>
        <td><%= import_error.description %></td>
        <td><%= link_to 'Show', import_error %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @import_errors, renderer: BootstrapPagination::Rails %>

app/views/import_errors/new.html.erb
<h1>New Import Error</h1>

<%= render 'form', import_error: @import_error %>

<%= link_to 'Back', import_errors_path %>

app/views/import_errors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Import:</strong>
  <%= @import_error.import_id %>
</p>

<p>
  <strong>Column:</strong>
  <%= @import_error.column %>
</p>

<p>
  <strong>Value:</strong>
  <%= @import_error.value %>
</p>

<p>
  <strong>Description:</strong>
  <%= @import_error.description %>
</p>

<%= link_to 'Edit', edit_import_error_path(@import_error) %> |
<%= link_to 'Back', import_errors_path %>