config/routes.rb
Rails.application.routes.draw do
  resources :import_errors
  resources :lead_errors
  resources :leads do
    resources :lead_errors
  end
  resources :imports do
    resources :import_errors
  end
  devise_for :users
  get "/columns", to: "column#index"
  mount Sidekiq::Web => "/sidekiq"
  root to: "imports#index"
end

app/models/lead.rb
class Lead < ApplicationRecord
  belongs_to :user
  belongs_to :import

  has_many :lead_errors

  validates :user, presence: true
  validates :import, presence: true
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :set_lead, only: %i[ show edit update destroy ]

  # GET /leads or /leads.json
  def index
    @leads = current_user.leads.paginate(page: params[:page])
  end

  # GET /leads/1 or /leads/1.json
  def show
  end

  # GET /leads/new
  def new
    @lead = Lead.new
  end

  # GET /leads/1/edit
  def edit
  end

  # POST /leads or /leads.json
  def create
    @lead = Lead.new(lead_params)

    respond_to do |format|
      if @lead.save
        format.html { redirect_to @lead, notice: "Lead was successfully created." }
        format.json { render :show, status: :created, location: @lead }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leads/1 or /leads/1.json
  def update
    respond_to do |format|
      if @lead.update(lead_params)
        format.html { redirect_to @lead, notice: "Lead was successfully updated." }
        format.json { render :show, status: :ok, location: @lead }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leads/1 or /leads/1.json
  def destroy
    @lead.destroy
    respond_to do |format|
      format.html { redirect_to leads_url, notice: "Lead was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lead
      @lead = current_user.leads.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lead_params
      params.require(:lead).permit(:user_id, :name, :birth_at, :phone, :address, :franchise, :encrypted_credit_card_number, :email)
    end
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/views/leads/_form.html.erb
<%= form_with(model: lead) do |form| %>
  <% if lead.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lead.errors.count, "error") %> prohibited this lead from being saved:</h2>

      <ul>
        <% lead.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :birth_at %>
    <%= form.date_select :birth_at %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :franchise %>
    <%= form.text_field :franchise %>
  </div>

  <div class="field">
    <%= form.label :encrypted_credit_card_number %>
    <%= form.text_field :encrypted_credit_card_number %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/leads/edit.html.erb
<h1>Editing Lead</h1>

<%= render 'form', lead: @lead %>

<%= link_to 'Show', @lead %> |
<%= link_to 'Back', leads_path %>

app/views/leads/index.html.erb
<h1>Leads</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Birth at</th>
      <th scope="col">Phone</th>
      <th scope="col">Address</th>
      <th scope="col">Franchise</th>
      <th scope="col">Email</th>
      <th scope="col" colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @leads.each do |lead| %>
      <tr>
        <td scope="row"><%= lead.name %></td>
        <td><%= lead.birth_at %></td>
        <td><%= lead.phone %></td>
        <td><%= lead.address %></td>
        <td><%= lead.franchise %></td>
        <td><%= lead.email %></td>
        <td><%= link_to 'Show', lead %></td>
        <td><%= link_to 'Edit', edit_lead_path(lead) %></td>
        <td><%= link_to 'Destroy', lead, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td>
          <% if lead.lead_errors.present? %>
            <%= link_to 'Errors', lead_lead_errors_path(lead) %>
          <% else %>
            <span>No Errors</span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @leads, renderer: BootstrapPagination::Rails %>

app/views/leads/new.html.erb
<h1>New Lead</h1>

<%= render 'form', lead: @lead %>

<%= link_to 'Back', leads_path %>

app/views/leads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @lead.user_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @lead.name %>
</p>

<p>
  <strong>Birth at:</strong>
  <%= @lead.birth_at %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @lead.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @lead.address %>
</p>

<p>
  <strong>Franchise:</strong>
  <%= @lead.franchise %>
</p>

<p>
  <strong>Encrypted credit card number:</strong>
  <%= @lead.encrypted_credit_card_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @lead.email %>
</p>

<%= link_to 'Edit', edit_lead_path(@lead) %> |
<%= link_to 'Back', leads_path %>