config/routes.rb
Rails.application.routes.draw do
  resources :import_errors
  resources :lead_errors
  resources :leads do
    resources :lead_errors
  end
  resources :imports do
    resources :import_errors
  end
  devise_for :users
  get "/columns", to: "column#index"
  mount Sidekiq::Web => "/sidekiq"
  root to: "imports#index"
end

app/models/import.rb
class Import < ApplicationRecord
  enum status: { on_hold: 0, processing: 1, failed: 2, finished: 3 }
  has_many :import_columns
  has_many :columns, through: :import_columns
  has_many :import_errors
  has_many :leads
  has_many :lead_errors, through: :leads
  belongs_to :user

  has_one_attached :file

  validates :file, attached: true, content_type: ["text/csv", "application/csv", "text/comma-separated-values"]

  accepts_nested_attributes_for :import_columns, allow_destroy: true

  after_create_commit :call_impoerter_worker

  def has_error?
    import_errors.present?
  end

  private
  def call_impoerter_worker
    ImporterWorker.perform_async(user_id, id)
  end
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  before_action :set_import, only: %i[ show edit update destroy ]

  # GET /imports or /imports.json
  def index
    @imports = current_user.imports.paginate(page: params[:page])
  end

  # GET /imports/1 or /imports/1.json
  def show
  end

  # GET /imports/new
  def new
    @import = Import.new
  end

  # GET /imports/1/edit
  def edit
  end

  # POST /imports or /imports.json
  def create
    @import = Import.new(import_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @import.save
        format.html { redirect_to @import, notice: "Import was successfully created." }
        format.json { render :show, status: :created, location: @import }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @import.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /imports/1 or /imports/1.json
  def update
    respond_to do |format|
      if @import.update(import_params)
        format.html { redirect_to @import, notice: "Import was successfully updated." }
        format.json { render :show, status: :ok, location: @import }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @import.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /imports/1 or /imports/1.json
  def destroy
    @import.destroy
    respond_to do |format|
      format.html { redirect_to imports_url, notice: "Import was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_import
      @import = current_user.imports.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def import_params
      params.require(:import).permit(:file, import_columns_attributes: [ :id, :column_id, :order, :_destroy ])
    end
end

app/helpers/imports_helper.rb
module ImportsHelper
end

app/views/imports/_form.html.erb
<%= form_with(model: import) do |form| %>
  <% if import.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(import.errors.count, "error") %> prohibited this import from being saved:</h2>

      <ul>
        <% import.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :file, class: "form-label" %>
    <%= form.file_field :file, class: "form-control" %>
  </div>

  <div class="card">
    <h5 class="card-title">Column map</h5>
    <div class="card-body">


      <ul class="list-group" id="list-of-columns">
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <div class="input-group col-md-6">
            <%= select_tag "people", nil, prompt: "Select something", class: "form-select", id: "selected-column" %>
            <button class="btn btn-outline-secondary" type="button" id="button-add-new-column">Add New Column</button>
          </div>
        </li>
        <%= form.fields_for :import_columns do |import_columns_fields| %>
          <li class="list-group-item d-flex justify-content-between align-items-center item-import-columns-live">
            <span class="column-name"><%= import_columns_fields.object.column.name %></span>
            <button class="btn btn-outline-danger button-column-remove" type="button"><%= import_columns_fields.object.order %></button>
            <%= import_columns_fields.hidden_field :order, class: "order" %>
            <%= import_columns_fields.hidden_field :column_id, class: "column_id" %>
            <%= import_columns_fields.hidden_field :_destroy, class: "_destroy" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>


  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/imports/edit.html.erb
<h1>Editing Import</h1>

<%= render 'form', import: @import %>

<%= link_to 'Show', @import %> |
<%= link_to 'Back', imports_path %>

app/views/imports/index.html.erb
<h1>Imports</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">When</th>
      <th scope="col">Status</th>
      <th scope="col" colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @imports.each do |import| %>
      <tr>
        <td scope="row"><%= l import.created_at %></td>
        <td><%= import.status %></td>
        <td><%= link_to 'Show', import %></td>
        <td>
          <% if import.import_errors.present? %>
            <%= link_to 'Errors', import_import_errors_path(import) %>
          <% else %>
            <span>No Errors</span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @import_errors, renderer: BootstrapPagination::Rails %>

<br>

<%= link_to 'New Import', new_import_path %>

app/views/imports/new.html.erb
<h1>New Import</h1>

<%= render 'form', import: @import %>

<%= link_to 'Back', imports_path %>

app/views/imports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @import.status %>
</p>

<%= link_to 'Edit', edit_import_path(@import) %> |
<%= link_to 'Back', imports_path %>