config/routes.rb
Rails.application.routes.draw do
  resources :import_errors
  resources :lead_errors
  resources :leads do
    resources :lead_errors
  end
  resources :imports do
    resources :import_errors
  end
  devise_for :users
  get "/columns", to: "column#index"
  mount Sidekiq::Web => "/sidekiq"
  root to: "imports#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def controller?(*controller)
    return "nav-link active" if controller.include?(params[:controller])
    "nav-link"
  end
end

app/views/application/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Contacts</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <% unless user_signed_in? %>
        <span class="d-flex">
          <div class="btn-group btn-group-sm" role="group" aria-label="Basic mixed styles example">
            <%= link_to "registration", new_user_registration_path, class: "btn btn-success" %>
            <%= link_to "signin", new_user_session_path, class: "btn btn-warning" %>
          </div>
        </span>
      <% else %>

        <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
          <li class="nav-item">
            <%= link_to leads_path, class: controller?('leads') do %>
              <%= "Leads" %>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to imports_path, class: controller?('imports') do %>
              <%= "Imports" %>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to import_errors_path, class: controller?('import_errors') do %>
              <%= "Import Errors" %>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to lead_errors_path, class: controller?('lead_errors') do %>
              <%= "Lead Errors" %>
            <% end %>
          </li>
        </ul>

        <span class="d-flex">
          <div class="btn-group btn-group-sm" role="group" aria-label="Basic mixed styles example">
            <%= link_to edit_user_registration_path, class: 'btn btn-warning' do %>
              <%= "configuration" %>
            <% end %>
            <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-success'  do %>
              <%= "signout" %>
            <% end %>
          </div>
        </span>
      <% end %>
    </div>
  </div>
</nav>